version: '3.6'
services:
  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    expose:
      - 27017
    volumes:
      - streaming-db:/data/db
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
volumes:
  streaming-db: