version: '3.6'
services:
  my-sql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'orderdb'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-sql:/var/lib/mysql
volumes:
  my-sql: